---

- name: Debian | set automysqlbackup_loaded_os_family
  set_fact:
    automysqlbackup_loaded_os_family: "{{ ansible_os_family  }}"
  tags:
    - automysqlbackup

- name: Debian | run apt update
  become: yes
  apt: update_cache=yes
  tags:
    - automysqlbackup

- name: Debian | install automysqlbackup
  become: yes
  apt: pkg=automysqlbackup state=latest
  tags:
    - automysqlbackup
