---
- name: Get automysqlbackup
  unarchive:
    copy: no
    src: "http://downloads.sourceforge.net/project/automysqlbackup/AutoMySQLBackup/AutoMySQLBackup%20VER%203.0/automysqlbackup-v3.0_rc6.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fautomysqlbackup%2F&ts=1454612617&use_mirror=iweb"
    dest: /opt/

- name: Create the /etc/automysqlbackup directory.
  file:
    path: /etc/automysqlbackup
    state: directory

- name: Copy in the automysqlbackup.conf file.
  command: cp /opt/automysqlbackup.conf /etc/automysqlbackup/automysqlbackup.conf

- name: Copy the automysqlbackup file to /usr/local/bin and make executable.
  copy:
    src: /opt/automysqlbackup
    dest: /usr/local/bin/
    remote_src: yes
    mode: 0750

- name: apply automysqlbackup configuration
  become: yes
  template:
    src: automysqlbackup.conf.j2
    dest: /etc/automysqlbackup/myserver.conf
    group: root
    owner: root
    mode: 0600
  tags:
    - automysqlbackup

- name: remove the cron.daily file
  become: yes
  file: path=/etc/cron.daily/automysqlbackup state=absent
  tags:
    - automysqlbackup

- name: add automysqlbackup cron job
  become: yes
  cron:
    name: "automysqlbackup"
    minute: "{{ automysqlbackup_cron.minute }}"
    hour: "{{ automysqlbackup_cron.hour }}"
    day: "{{ automysqlbackup_cron.day }}"
    month: "{{ automysqlbackup_cron.month }}"
    weekday: "{{ automysqlbackup_cron.weekday }}"
    user: root
    job: "/usr/local/bin/automysqlbackup /etc/automysqlbackup/myserver.conf"
  tags:
    - automysqlbackup
